[bastion]
bastion ansible_host=3.110.127.92

[webservers]
web1 ansible_host=10.0.2.82
web2 ansible_host=10.0.2.131

[mongodb]
db ansible_host=10.0.2.166

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/AWS.pem

[webservers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/AWS.pem -o StrictHostKeyChecking=no ubuntu@3.110.127.92"'

[mongodb:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/AWS.pem -o StrictHostKeyChecking=no ubuntu@3.110.127.92"'